/** Curated PawFeed release notes derived from the fork commit history (Tony Pup). */

export interface ChangelogSection {
  /** ISO date for sorting / stable keys */
  date: string;
  /** Short section heading */
  title: string;
  items: string[];
}

/**
 * Newest first. Sourced from all Tony Pup commits since the Sep 2026 fork
 * push (e621/e6ai profiles through Unified, Local, and the multi-site stack).
 * Upstream Material e621 history lives on GitHub / the About page.
 */
export const changelogSections: ChangelogSection[] = [
  {
    date: "2026-09-21",
    title: "Go to top, News polish, and more News sources",
    items: [
      "Posts search feed shows a floating Go to top button after you scroll (list and grid), pinned for mobile safe areas and tip toasts",
      "Go to top sits bottom-right of the viewport so it stays clear of the floating sidebar",
      "News prefers full WordPress content:encoded bodies over short RSS excerpts (Dogpatch articles read complete in-app)",
      "News saved filters snapshot source, Flayrah section, and view so Dogpatch Unread reopens correctly",
      "Flayrah taxonomy chips only show when filtering to Flayrah; SFW only is hidden in News (it never applied there)",
      "Saved News articles keep a body snapshot and offline cache evicts by last opened; mark unread (u), mark filtered read, and a sidebar unread badge",
      "News reader: j/k scrolls the focused row, magazine cards match the list, relative dates, Go to top, author:/tag:/source: filters, embed links instead of blank players, Flayrah-only figure float, and a first-visit tip",
      "Dogpatch category chips (allowlisted feeds) and Load older for WordPress-paged sources; Flayrah’s public RSS is not paged",
      "News feed groups headlines by day; article reader has text size and column width controls plus click-to-enlarge images",
      "News source registry plus InFurNation and Furry Writers’ Guild in the merged feed (Atom parse when a feed is Atom)",
      "News can cluster the same story across outlets (“also on…”), watch authors locally, and optionally highlight headlines newer than your last visit",
    ],
  },
  {
    date: "2026-09-20",
    title: "News mode: Flayrah + Dogpatch Press",
    items: [
      "Flayrah site mode is now News: one merged date-sorted feed from Flayrah and Dogpatch Press with source filter chips",
      "Routes moved to /news (legacy /flayrah redirects); article ids are namespaced (flayrah:123 / dogpatch:456) with saved/read migration",
      "Dogpatch Press full public RSS is included with attribution and open-on-source links; Flayrah taxonomy chips still apply when filtering to Flayrah",
    ],
  },
  {
    date: "2026-09-20",
    title: "Clearer Suggester and Analyzer tips",
    items: [
      "SFW only: typing rating:safe or rating:s on e621-family, Furbooru, FurAffinity, or Federated turns SFW on; Federated no longer toasts when that injected safe rating is dropped on sites without rating search (e.g. SoFurry)",
      "One-time tips appear as bottom-right toasts (not center dialogs), with Don't show this again and OK; tips queue one at a time and snackbars stack above them",
      "Tip toasts on phones use a full-width bottom bar with safe-area padding and a full-width OK control",
      "Federated Post Suggester seeds hybrid searches per child from that child's favorite tags (no cross-origin seed pollution)",
      "Blocked tools under Tailspace (Dashboard, Pools, Saved, Suggester, Analyzer) redirect to Tailspace posts instead of e621-shaped Posts",
      "On e621, e6ai, FurAffinity, and SoFurry, leave the Suggester/Analyzer username blank when signed in to use your own favorites",
      "FurAffinity own-favorites in Suggester/Analyzer require profile cookies or host FA_COOKIE_* (looking up another user still works without cookies)",
      "Federated Post Suggester and Favorite Analyzer snackbar when some sites fail to load favorites and others still succeed",
      "Federated Post Suggester and Favorite Analyzer sample favorites from every enabled child even when the Posts feed is on Following",
      "Post Suggester and Favorite Analyzer page through favorites correctly on sites whose APIs return fewer than 320 posts per page",
      "Post Suggester and Favorite Analyzer first-visit tips explain how each tool works in plain language (Appearance → Reset tooltips to see them again)",
      "Post Suggester and Favorite Analyzer pages include a short on-page primer of how each tool works",
    ],
  },
  {
    date: "2026-09-18",
    title: "Federated Pools site toggles",
    items: [
      "Mobile drawer closes after navigation; hamburger matches the mobile breakpoint (no dead toggle on tablets)",
      "Fullscreen uses dynamic viewport height and safe-area padding; comments open full-bleed on phones",
      "Compact cards on touch: first tap expands chrome, second opens the post",
      "Settings switch between full-page (phone) and overlay (desktop) when resizing; Local folder copy clarifies desktop Chromium / Tauri",
      "Posts search history stays on the toolbar on phones; PWA display is standalone; offline snackbar can switch to Local or Flayrah",
      "DText spoilers reveal on tap or focus (not hover-only); mobile Playwright projects cover Pixel 7 / iPhone 13 / iPad Mini",
      "Mobile sidebar is narrower (300px) and has a close button so it no longer covers the whole screen",
      "Landing no longer opens on Federated after a previous Federated session; it restores the prior site (or e621), unless you navigated back from Browse posts",
      "Baxter logo refresh: longer basset ears, clearer tail, PawFeed wordmark in Fredoka, double-blink and a tilted loader pulse; favicon matches",
      "Desktop Settings open as an overlay over the current page (mobile stays full-page); landing gear opens Settings from the hero and footer",
      "Landing Changelog & TOS renamed to Info, with an About tab (version, license, credits) beside Changelog and TOS",
      "Landing hero Settings gear matches the height of the Info / Scent Marks actions",
      "Federated Pools: Sites in Pools sidebar toggles sit between Pools and Post Suggester (e621/e6ai/Furbooru/Inkbunny plus Tailspace comics)",
      "Include Tailspace comics moved out of Account settings into that Pools sidebar (still on by default)",
      "Furbooru pool cards: cover thumbnails load again (Philomena Everything filter + id:a,b,c → OR); hide stub epoch dates and unknown page counts on the list",
      "Pool cards show a static gray image icon while covers load (with a shared Loading typewriter cycle) and image-off when missing/failed; cover downloads are deferred/limited to the near viewport",
      "Federated Pools: Tailspace comic cover thumbnails load again (pics.tailspace.com allowlisted on /api/download)",
      "Landing hero under PawFeed types a random furry/pup splash once and leaves it on screen (click or Enter/Space for another); the site-summary line moves above What it does",
      "Mode-switch toast says Switched to Federated (not unified)",
      "SFW only toggle (toolbar, sidebar, and Post settings): forces safe rating across sites, overrides rating search tags, and hides non-safe posts in list feeds (direct links still open)",
    ],
  },
  {
    date: "2026-09-17",
    title: "PawFeed, Flayrah, Federated Pools, and hardening",
    items: [
      "Product renamed to PawFeed; public Live URL is pawfeed.tonypup.box.ca (host paths and GitHub stay m-e621)",
      "App logo and favicon refreshed to a basset-hound mark; loading spinner matches the sidebar face",
      "Logo face raised to shorten the forehead; blink lids no longer cover the eyebrows",
      "Flayrah site mode: read-only RSS feed and article reader with taxonomy chips, archive, saved/unread, magazine layout, and j/k shortcuts",
      "Federated Pools: merged e621/e6ai browse with origin badges, sequential fetch/retry, and Updated/sort interleave",
      "Inkbunny pools: site-mode /pools with open-by-id and watch; Federated reader via ?origin=inkbunny (no free-text IB name search)",
      "Federated Watched Pools includes Inkbunny when that child is enabled; pool chips open the shared reader",
      "Furbooru galleries: site-mode /pools plus Federated name browse/reader via ?origin=furbooru (Philomena search/galleries; tag browse stays e621/e6ai)",
      "Federated Pools name browse can include Tailspace comics (sidebar Sites in Pools, on by default); opens the Tailspace reader",
      "Federated Watched Pools & Comics aggregates e621/e6ai watched pools and Tailspace watched comics when Tailspace comics is on; eye toggle writes to the same per-source lists",
      "Federated Pools interleave Tailspace comics with e621/e6ai by Updated/sort (ISO comic dates parse correctly)",
      "Site mode renamed from Unified to Federated; sidebar Defaults / Auth-only presets sit as a compact toolbar",
      "Landing Federated chips: multi-select sites for search inclusion, close/label exits to the previous site, and a one-time tip (Appearance → Reset tooltips)",
      "More one-time tips (Reset tooltips): Federated Following, Local library, Layout shortcuts, pool origin/watched badges, watched comics, pool reader, fullscreen gestures, Saved posts, blacklist modes, Tailspace comics, Fluffle, remux, Suggester, Analyzer, Flayrah offline cache, starred tags",
      "Layout menu and Post settings: Infinite scroll toggle (off uses previous/next); Saved posts share the same Layout menu",
      "Pools: watched +N badges, chunk/deep-link resume, fullscreen across chunks, hidden-page placeholders, Save chunk / Save all",
      "Pool fullscreen next/prev keeps the dialog open (no pool reload on ?post= sync)",
      "Tailspace Comics: local Watched Comics strip with eye toggle, +N new-page badges, and a one-time tip",
      "Scent Marks: host pin-to-top, unlock-gated moderation, rate-limited admin actions; feed heading is Scent Trail",
      "Landing: tag wiki snippets (Another page), darkened copy panels for Transparent Zen, Scent Marks / Browse no longer blank",
      "Landing What it does / What is PawFeed copy refreshed for Federated Search·Following, layouts, Fluffle, and watched pools",
      "Hardened media download and Fluffle redirects (allowlisted hops); Docker ships the Scent Trail blocklist",
      "Federated Post Suggester and Favorite Analyzer use per-child auth; clearer empty-sample errors",
      "Posts Back / ?page= reload; mode redirects keep query params; stars:me remaps on non-Itaku Federated children",
      "Settings: safer backup/restore, per-site account panels, color scheme, data-saver Automatic, synonym search",
      "Local Tauri: MP4 ftyp sniff for mislabeled MPEG-TS; sidecar tag edits use the merge lock",
      "Furbooru rejects HTML error pages before JSON parse; Federated/Local autocomplete no longer hits e621",
      "Federated site inclusion (chips / Defaults / Auth-only) persists when leaving and re-entering Federated",
      "Dev download proxy allows Flayrah media hosts; notes/votes/comments no longer fall through to e621 on other modes",
      "Pools, comments, and notes requests send Basic auth when the profile has credentials",
      "Tailspace/Flayrah redirect away from the Parser debug route; oxlint ignores vendored ffmpeg/Ruffle",
      "Account site logins use autocomplete=new-password so password managers stop fighting settings panels",
      "ESLint clean across src: typed catches, removed Vuetify MD2 props, historical single-word page names ignored",
    ],
  },
  {
    date: "2026-09-16",
    title: "Unified Following, Local writes, and polish",
    items: [
      "Artist Dashboard: clearer heatmap, top-post previews, honest weekly rate, richer filters, and add-as-saved-search",
      "Post Suggester and Favorite Analyzer on all modes except Tailspace",
      "Unified Search vs Following feed, with Defaults and Auth-only site presets",
      "Watched pools on the e621-family pool browser; Furbooru post comments",
      "Landing: site chips, About strip, Changelog & TOS dialog with fair-use summaries",
      "Scent Marks: anonymous guestbook with host moderation, hate/CSAM/spam blocklist, clearer contrast",
      "Tauri Local writes under the browse root; portable favorites/resume sidecars; Save Locally `%origin%`",
      "Separate audio mute / volume / speed; optional paw cursor; fairer Random (Fisher–Yates)",
      "Offline: remote modes disabled; Local stays available",
      "SoFurry likes / Remix auth and story formatting; Weasyl and Itaku on by default in Unified Search",
      "Self-host `sync` lock serializes overlapping deploys and no longer sticks after restart",
    ],
  },
  {
    date: "2026-09-15",
    title: "More sites, stories, Fluffle, and reading UX",
    items: [
      "SoFurry and Itaku site modes (comments on Itaku)",
      "Weasyl as a site mode and optional Unified child",
      "FurAffinity mode with cookie sign-in and captcha login helper",
      "Fluffle reverse image search with copy-URL on results",
      "Fullscreen comments rail with resizable dual prefs; info + description in-rail",
      "Story / PDF / RTF / DOCX fullscreen preview; story titles on cards",
      "Music playback on remote site modes; music card badges",
      "Pools: thumbnails, sort, ordered reading, tag search, gallery/scroll reader",
      "Feed GIF/video animate + autoplay settings; unload off-screen video buffers",
      "Mode-independent saved posts; bookmark from any federated site",
      "History navigation; denser settings groups with hub search",
      "Tailspace login and interactive features",
      "Compact sidebar site switcher; origin badge icons",
      "Furbooru Cloudflare / Philomena challenge workarounds and media hydration",
    ],
  },
  {
    date: "2026-09-14",
    title: "Unified federation and public rebrand",
    items: [
      "Unified site mode: date-merge federated posts from child sites",
      "Toggle Unified child sites from the posts sidebar",
      "Shared Score / Favs / Random controls and search groups",
      "Landing site picker / mode chips",
      "Clearer site icons and comic full-width scroll",
      "Public rebrand as m-e621 (AGPL fork of Material e621)",
      "e621 media proxy for Firefox / Zen video playback",
    ],
  },
  {
    date: "2026-09-13",
    title: "Local library, Tailspace, Inkbunny, Furbooru, and foundations",
    items: [
      "Per-mode e621 / e6ai profiles",
      "Local site mode: browse save folder, posters, remux, favorites, fuzzy tags, Random",
      "Tailspace posts and comics with in-app page reader and scroll mode",
      "Furbooru site mode with API key auth",
      "Inkbunny hybrid site mode",
      "Ruffle Flash / SWF playback",
      "Zen Browser / Transparent Zen compatibility",
      "Save Locally, full-width feed, starred tag folders, slideshow, card auto-next",
      "Inline feed video; Score and Favs on the search bar",
      "Sidebar saved-search management",
      "Same-origin download and favorites proxies; self-hosted sync / git-pull control",
      "Large bugfix pass and landing “Tony / Avoonix” update columns",
    ],
  },
];

export const changelogIntro =
  "PawFeed is a personal multi-site fork of Material e621. Highlights below cover the fork’s shipped work; older upstream commits are on GitHub.";
