/** Random landing hero splash lines (furry / pup-play motif). */

export const LANDING_SPLASHES: readonly string[] = [
  "Who's a good browser? You are. Yes you are.",
  "*tail wagging intensifies*",
  "Fetch! ...the next page.",
  "Good pup. Have a treat.",
  "Zoomies enabled.",
  "Warning: may cause uncontrollable tail wagging.",
  "Sit. Stay. Scroll.",
  "Belly rubs accepted as payment.",
  "Ear scritches improve load times by 12%.",
  "This app has been a very good boy.",
  "Now with 100% more good-dog energy.",
  "Bark twice for the next page.",
  "Kennel-tested, puppy-approved.",
  "Roll over and check the tags.",
  "Paws on keyboard. Eyes on art.",
  "Wanna go for a walk? (To the next page?)",
  "Fetch the API. Good worker!",
  "Who's a good federation? Yes you are.",
  "The best boy of imageboard browsers.",
  "Sniff sniff... new posts!",
  "Treats for tags.",
  "Headpats for every successful load.",
  "Naps are a valid browsing strategy.",
  "Rolled over. Got a belly rub. 10/10.",
  "Yiff responsibly.",
  "Now 20% fluffier.",
  "Warning: contains fur.",
  "Sniffing out posts since launch.",
  "Furry enough to browse.",
  "Powered by fur, caffeine, and questionable decisions.",
  "Scalies welcome too.",
  "Anthro-approved.",
  "Contains traces of fursuit.",
  "Snoot-booped.",
  "Boop the snoot to continue.",
  "Muzzle-friendly UI.",
  "Paw-approved, claw-tested.",
  "This post is not a fursuit. Probably.",
  "Tail floof levels: maximal.",
  "Ears perked for new uploads.",
  "Scent-marked and proud.",
  "Every pup has its day.",
  "The fluff is strong with this one.",
  "Fursuit Friday, every Friday.",
  "Pawsitively delightful.",
  "Furtastic.",
  "A-mutt-zing.",
  "I'm not a furry, I just browse here.",
  "Fetch-ingly good.",
  "Howl about that?",
  "Fur the win.",
  "It's a ruff life.",
  "Paws and effect.",
  "Tail-waggingly good.",
  "Nine sites, one feed, zero regrets.",
  "Federated and loving it.",
  "All your boards in one basket.",
  "Unifying the furry internet.",
  "Now with furry news!",
  "It's not hoarding if it's federated.",
  "Tag translation: engaged.",
  "Merging timelines like it's nothing.",
  "One app to pet them all.",
  "Home of the 40-tag cap.",
  "Blacklisting with love.",
  "e621's finest, rendered locally.",
  "Furbooru, but with fewer Cloudflare tears.",
  "Inkbunny galleries, unwrapped.",
  "FurAffinity, without the HTML scraping (well, mostly).",
  "Weasyl guests stay SFW. You're welcome.",
  "Itaku stars, aligned.",
  "SoFurry stories, fully readable.",
  "Tailspace comics, tail-waggingly scrollable.",
  "News headlines, cached for offline naps.",
  "Diving into the pool.",
  "Pool party!",
  "Reader mode: activated.",
  "Comic panels aligned.",
  "Page 1 of many. Good luck.",
  "Chunk by chunk, we ride.",
  "Watch the pool. Wag at updates.",
  "Next page keeps the dialog open. As it should.",
  "Fullscreen fur.",
  "Immersive mode: engaged.",
  "Now with sound! You're welcome.",
  "Booping at full resolution.",
  "Zoomed in for the details.",
  "Notes overlaid, snoot approved.",
  "Settings are for the weak. Also for you.",
  "Config version 46. Don't ask.",
  "Now with more profiles!",
  "Backups that don't bite.",
  "AGPL: share the love (and the source).",
  "Made with love, fur, and TypeScript.",
  "Warning: may contain traces of AI.",
  "Powered by Vue 3 and questionable life choices.",
  "No animals were harmed. Some code was.",
  "If found, return to pawdeck.tonypup.box.ca.",
  "This splash text is a good boy.",
  "Offline mode: napping.",
  "Press F to pet.",
  "Ctrl+Wag.",
  "Ctrl+Belly Rub.",
  "Alt+Tail Wag.",
  "Shift+Scritch.",
  "Tab to the dog park.",
  "Enter to fetch.",
  "Esc to run away.",
  "Space to pounce.",
  "Arrow keys to trot along.",
  "Who let the pups out? (You did. Good job.)",
  "Collar optional. Tags mandatory.",
  "Good boys browse responsibly.",
  "Pet the refresh button. Gently.",
  "Leash optional. Infinite scroll recommended.",
  "Sit pretty while the feed loads.",
  "Your snoot knows best.",
  "Pack-approved browsing client.",
  "Wiggle your toes. Wait\u2014paws.",
  "Treat dispenser: enabled.",
  "Downward dog? No, sideways scroll.",
  "Alpha of the browser tab.",
  "Beta? More like good boy.",
  "Omega of offline caches.",
  "Crate training complete. Ship it."
];

export function pickLandingSplash(exclude?: string): string {
  const pool = LANDING_SPLASHES;
  if (pool.length === 0) return "";
  if (pool.length === 1) return pool[0]!;
  let next = pool[Math.floor(Math.random() * pool.length)]!;
  if (exclude && pool.length > 1) {
    let guard = 0;
    while (next === exclude && guard++ < 8) {
      next = pool[Math.floor(Math.random() * pool.length)]!;
    }
  }
  return next;
}
